version: '2.24.6'

services:
  node-emr-backend:
    restart: always
    container_name: node-emr-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    container_name: postgres-emr-project
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: emr-postgres
      POSTGRES_DB: emr-project
      PGDATA: /database/postgres

    volumes:
      - ./database/pg:/data/postgres
