version: '2.24.6'

services:
  postgres:
    container_name: postgres-emr-project
    image: postgres
    ports:
      - 5555:5555
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: emr-postgres
      POSTGRES_DB: emr-project
      PGDATA: /database/postgres
    volumes:
      - ./database/pg:/data/postgres